CREATE DATABASE TEAMS;
USE TEAMS;

CREATE TABLE ALUNO( 
    ID_ALUNO INT PRIMARY KEY AUTO_INTERMENT,
    NOME_ALUNO VARCHAR(25) NOT NULL,
    EMAIL_ALUNO VARCHAR(25) NOT NULL,
    SENHA_ALUNO VARCHAR(15) NOT NULL
);

CREATE TABLE PROFESSOR(
    ID_PROFESSOR INT PRIMARY KEY AUTO_INTERMENT,
    NOME_PROFESSOR VARCHAR(25) NOT NULL,
    EMAIL_PROFESSOR VARCHAR(25) NOT NULL,
    SENHA_PROFESSOR VARCHAR(15) NOT NULL
);

CREATE TABLE TAREFA( 
    ID_TAREFA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_TAREFA VARCHAR(25) NOT NULL,
    DESCRICAO_TAREFA VARCHAR(50) NOT NULL,
    MATERIAL_COMPLEMENTAR_TAREFA VARCHAR(100) NOT NULL
);

CREATE TABLE TAREFA_PROFESSOR(
    ID_TAREFA INT,
    ID_PROFESSOR INT,
    CONSTRAINT PROFESSOR_TAREFA_PK PRIMARY KEY (ID_TAREFA, ID_PROFESSOR),
    CONSTRAINT TAREFA_PROFESSOR_TAREFA_FK FOREIGN KEY(ID_TAREFA) REFERENCES TAREFA(IDTAREFA),
    CONSTRAINT TAREFA_PROFESSOR_PROFESSOR_FK FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR)
);

INSERT INTO ALUNO (NOME_ALUNO, EMAIL_ALUNO, SENHA_ALUNO) VALUES ("Sergio Cristiano", "sergio@gmail.com", "serigio11");
INSERT INTO ALUNO (NOME_ALUNO, EMAIL_ALUNO, SENHA_ALUNO) VALUES ("Claudia Amanaque", "amanaque@gmail.com", "claudia2");
INSERT INTO ALUNO (NOME_ALUNO, EMAIL_ALUNO, SENHA_ALUNO) VALUES ("Joao Vargas", "vargas@gmail.com", "joaoooo");
INSERT INTO ALUNO (NOME_ALUNO, EMAIL_ALUNO, SENHA_ALUNO) VALUES ("Paulo Gustavo Andrade", "andrade@gmail.com", "andradea");
INSERT INTO ALUNO (NOME_ALUNO, EMAIL_ALUNO, SENHA_ALUNO) VALUES ("Uriel Franca", "andrade@gmail.com", "andradea");

UPDATE ALUNO SET NOME_ALUNO = "Ronaldo Freitas" WHERE NOME_ALUNO = "Uriel Franca";
DELETE ALUNO WHERE NOME_ALUNO = "João Vargas"; 

SELECT * FROM TAREFA; 

SELECT NOME_PROFESSOR, NOME_TAREFA AS 'Prova', ID_PROFESSOR, ID_TAREFA
FROM PROFESSOR P
INNER JOIN PROFESSOR_TAREFA PT
ON P. ID_PROFESSOR = PT. ID_PROFESSOR
INNER JOIN TAREFA T
ON PT.ID_TAREFA = T.ID_TAREFA;